### ISSUE TITLE
Is it possible to provide some resources for SSO protocols? its just pretty common request from enterprises 

### ISSUE THREAD

**Issue by MrAlekhin** [warrant-dev/awesome-authorization#4]
- Like what are the options
- existing 3rd party solutions
- what can be considered an MVP project for SSO, just get a foot in the door

**Comment by akajla09** [comment]
IMO SSO is more of an authentication (identity/who you are) concern vs. an authorization (permissions/what you can do) one. Since this list focuses exclusively on authz, I don't think SSO necessarily fits as a topic.

That being said, I agree with you that more resources on best practices/implementation guides for SSO would be very useful. I personally don't have any to recommend at the moment. But I do know that Auth0, Okta and WorkOS are a few vendors with SSO offerings catered to b2b companies/enterprises.

**Comment by MrAlekhin** [comment]
Yes, makes sense 👍
